name: Run `npm start`

on:
  push:
    paths:
      - ./**.sketch
      - ./**.ts
      - .github/workflows/**.yml
    branches: [main]
  pull_request:
    paths:
      - ./**.sketch
      - ./**.ts
      - .github/workflows/**.yml
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 17.8.0
      - name: Install dependencies
        run: npm install
      - name: Run `npm start`
        run: npm start
      - uses: actions/upload-artifact@v2
        with:
          name: Updated Sample Sketch File
          path: sample-file.sketch
